from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFontDatabase

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 587)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 10, 381, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(20, 80, 381, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(390, 20, 21, 71))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(10, 20, 21, 71))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.button_1 = QtWidgets.QPushButton(Form)
        self.button_1.setGeometry(QtCore.QRect(40, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(Form)
        self.button_2.setGeometry(QtCore.QRect(130, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.button_3 = QtWidgets.QPushButton(Form)
        self.button_3.setGeometry(QtCore.QRect(220, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.button_plus = QtWidgets.QPushButton(Form)
        self.button_plus.setGeometry(QtCore.QRect(310, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_plus.setFont(font)
        self.button_plus.setObjectName("button_plus")
        self.button_4 = QtWidgets.QPushButton(Form)
        self.button_4.setGeometry(QtCore.QRect(40, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.button_5 = QtWidgets.QPushButton(Form)
        self.button_5.setGeometry(QtCore.QRect(130, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.button_6 = QtWidgets.QPushButton(Form)
        self.button_6.setGeometry(QtCore.QRect(220, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.button_minus = QtWidgets.QPushButton(Form)
        self.button_minus.setGeometry(QtCore.QRect(310, 210, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_minus.setFont(font)
        self.button_minus.setObjectName("button_minus")
        self.button_7 = QtWidgets.QPushButton(Form)
        self.button_7.setGeometry(QtCore.QRect(40, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.button_8 = QtWidgets.QPushButton(Form)
        self.button_8.setGeometry(QtCore.QRect(130, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.button_9 = QtWidgets.QPushButton(Form)
        self.button_9.setGeometry(QtCore.QRect(220, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.button_mult = QtWidgets.QPushButton(Form)
        self.button_mult.setGeometry(QtCore.QRect(310, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_mult.setFont(font)
        self.button_mult.setObjectName("button_mult")
        self.button_0 = QtWidgets.QPushButton(Form)
        self.button_0.setGeometry(QtCore.QRect(40, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.button_dot = QtWidgets.QPushButton(Form)
        self.button_dot.setGeometry(QtCore.QRect(130, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_dot.setFont(font)
        self.button_dot.setObjectName("button_dot")
        self.button_equals = QtWidgets.QPushButton(Form)
        self.button_equals.setGeometry(QtCore.QRect(220, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_equals.setFont(font)
        self.button_equals.setObjectName("button_equals")
        self.button_divide = QtWidgets.QPushButton(Form)
        self.button_divide.setGeometry(QtCore.QRect(310, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_divide.setFont(font)
        self.button_divide.setObjectName("button_divide")
        self.button_power = QtWidgets.QPushButton(Form)
        self.button_power.setGeometry(QtCore.QRect(40, 480, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_power.setFont(font)
        self.button_power.setObjectName("button_power")
        self.button_sqrt = QtWidgets.QPushButton(Form)
        self.button_sqrt.setGeometry(QtCore.QRect(130, 480, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_sqrt.setFont(font)
        self.button_sqrt.setObjectName("button_sqrt")
        self.button_factorial = QtWidgets.QPushButton(Form)
        self.button_factorial.setGeometry(QtCore.QRect(220, 480, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_factorial.setFont(font)
        self.button_factorial.setObjectName("button_factorial")
        self.button_clear = QtWidgets.QPushButton(Form)
        self.button_clear.setGeometry(QtCore.QRect(300, 470, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")
        self.calc_field = QtWidgets.QLabel(Form)
        self.calc_field.setGeometry(QtCore.QRect(50, 30, 311, 51))
        self.calc_field.setText("")
        self.calc_field.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.calc_field.setObjectName("calc_field")
        self.button_clear.setStyleSheet("background-color: orange; color: black")
        
        QFontDatabase.addApplicationFont("UI/digital-7.ttf")
        self.calc_field.setStyleSheet("""
        font-size: 36px;
        font-family: 'Digital-7'; 
        """)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_1.setText(_translate("Form", "1"))
        self.button_2.setText(_translate("Form", "2"))
        self.button_3.setText(_translate("Form", "3"))
        self.button_plus.setText(_translate("Form", "+"))
        self.button_4.setText(_translate("Form", "4"))
        self.button_5.setText(_translate("Form", "5"))
        self.button_6.setText(_translate("Form", "6"))
        self.button_minus.setText(_translate("Form", "-"))
        self.button_7.setText(_translate("Form", "7"))
        self.button_8.setText(_translate("Form", "8"))
        self.button_9.setText(_translate("Form", "9"))
        self.button_mult.setText(_translate("Form", "*"))
        self.button_0.setText(_translate("Form", "0"))
        self.button_dot.setText(_translate("Form", "."))
        self.button_equals.setText(_translate("Form", "="))
        self.button_divide.setText(_translate("Form", "/"))
        self.button_power.setText(_translate("Form", "^"))
        self.button_sqrt.setText(_translate("Form", "√"))
        self.button_factorial.setText(_translate("Form", "!"))
        self.button_clear.setText(_translate("Form", "C"))
