from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(549, 415)
        self.label_color1 = QtWidgets.QLabel(Form)
        self.label_color1.setGeometry(QtCore.QRect(50, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_color1.setFont(font)
        self.label_color1.setObjectName("label_color1")
        self.button_blue1 = QtWidgets.QRadioButton(Form)
        self.button_blue1.setGeometry(QtCore.QRect(40, 130, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_blue1.setFont(font)
        self.button_blue1.setObjectName("button_blue1")
        self.button_red1 = QtWidgets.QRadioButton(Form)
        self.button_red1.setGeometry(QtCore.QRect(40, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_red1.setFont(font)
        self.button_red1.setObjectName("button_red1")
        self.button_green1 = QtWidgets.QRadioButton(Form)
        self.button_green1.setGeometry(QtCore.QRect(40, 250, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_green1.setFont(font)
        self.button_green1.setObjectName("button_green1")
        self.button_green2 = QtWidgets.QRadioButton(Form)
        self.button_green2.setGeometry(QtCore.QRect(220, 250, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_green2.setFont(font)
        self.button_green2.setObjectName("button_green2")
        self.label_color2 = QtWidgets.QLabel(Form)
        self.label_color2.setGeometry(QtCore.QRect(230, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_color2.setFont(font)
        self.label_color2.setObjectName("label_color2")
        self.button_red2 = QtWidgets.QRadioButton(Form)
        self.button_red2.setGeometry(QtCore.QRect(220, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_red2.setFont(font)
        self.button_red2.setObjectName("button_red2")
        self.button_blue2 = QtWidgets.QRadioButton(Form)
        self.button_blue2.setGeometry(QtCore.QRect(220, 130, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_blue2.setFont(font)
        self.button_blue2.setObjectName("button_blue2")
        self.button_green3 = QtWidgets.QRadioButton(Form)
        self.button_green3.setGeometry(QtCore.QRect(400, 250, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_green3.setFont(font)
        self.button_green3.setObjectName("button_green3")
        self.label_color1_3 = QtWidgets.QLabel(Form)
        self.label_color1_3.setGeometry(QtCore.QRect(410, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_color1_3.setFont(font)
        self.label_color1_3.setObjectName("label_color1_3")
        self.button_red3 = QtWidgets.QRadioButton(Form)
        self.button_red3.setGeometry(QtCore.QRect(400, 190, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_red3.setFont(font)
        self.button_red3.setObjectName("button_red3")
        self.button_blue3 = QtWidgets.QRadioButton(Form)
        self.button_blue3.setGeometry(QtCore.QRect(400, 130, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_blue3.setFont(font)
        self.button_blue3.setObjectName("button_blue3")
        self.makeflag_button = QtWidgets.QPushButton(Form)
        self.makeflag_button.setGeometry(QtCore.QRect(370, 320, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.makeflag_button.setFont(font)
        self.makeflag_button.setObjectName("makeflag_button")
        self.result_label = QtWidgets.QLabel(Form)
        self.result_label.setGeometry(QtCore.QRect(40, 330, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.result_label.setFont(font)
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_color1.setText(_translate("Form", "Цвет №1"))
        self.button_blue1.setText(_translate("Form", "Синий"))
        self.button_red1.setText(_translate("Form", "Красный"))
        self.button_green1.setText(_translate("Form", "Зелёный"))
        self.button_green2.setText(_translate("Form", "Зелёный"))
        self.label_color2.setText(_translate("Form", "Цвет №2"))
        self.button_red2.setText(_translate("Form", "Красный"))
        self.button_blue2.setText(_translate("Form", "Синий"))
        self.button_green3.setText(_translate("Form", "Зелёный"))
        self.label_color1_3.setText(_translate("Form", "Цвет №3"))
        self.button_red3.setText(_translate("Form", "Красный"))
        self.button_blue3.setText(_translate("Form", "Синий"))
        self.makeflag_button.setText(_translate("Form", "Сделать флаг"))
